import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

live_config_reload = true

[env]
# wrong TERM setting prevents CopyPaste
# TERM = "screen-256color"
TERM = "xterm-256color"

[window]
option_as_alt = "OnlyLeft"
startup_mode = "Windowed"
dynamic_padding = true
decorations = "Buttonless"
opacity = 0.5
blur = false

[window.dimensions]
columns = 95
lines = 50

[window.padding]
x = 5
y = 5

[scrolling]
history = 50000
multiplier = 3

[font]
size = 14

  [font.normal]
  family = "FiraCode Nerd Font Mono"
  style = "Regular"

  [font.bold]
  family = "FiraCode Nerd Font Mono"
  style = "Bold"

  [font.italic]
  family = "FiraCode Nerd Font Mono"
  style = "Italic"

[cursor.style]
shape = "Beam"
blinking = "always"

[cursor]
unfocused_hollow = true

[selection]
save_to_clipboard = true

# [terminal]
# osc52 = "CopyPaste"
